import { Request, Response, NextFunction } from "express";
import { supabaseAdmin } from "./supabase";
import { db, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { sendWelcomeEmail } from "./email";

/**
 * Extract the best available name from Supabase user metadata.
 * Prefers real provider names (Google full_name, name) over email-derived fallbacks.
 * Returns null if no real name is found — so we can distinguish "no name" from "email prefix".
 */
function extractProviderName(supabaseUser: { user_metadata?: Record<string, any>; email?: string }): {
  realName: string | null;
  fallbackName: string;
} {
  const meta = supabaseUser.user_metadata ?? {};
  const realName =
    (meta.full_name as string | undefined)?.trim() ||
    (meta.name as string | undefined)?.trim() ||
    null;
  const fallbackName =
    realName ||
    supabaseUser.email?.split("@")[0] ||
    "Usuário";
  return { realName, fallbackName };
}

/**
 * Returns true if the given DB name looks auto-generated (email prefix or placeholder).
 * Used to decide whether a real provider name should override it.
 */
function isAutoGeneratedName(dbName: string, email: string): boolean {
  const emailPrefix = email.split("@")[0] ?? "";
  return dbName === emailPrefix || dbName === "Usuário" || dbName.trim() === "";
}

export async function authMiddleware(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.headers.authorization;
  const token = authHeader?.startsWith("Bearer ") ? authHeader.slice(7) : null;

  if (!token) {
    res.status(401).json({ error: "Unauthorized" });
    return;
  }

  const { data: { user: supabaseUser }, error } = await supabaseAdmin.auth.getUser(token);

  if (error || !supabaseUser) {
    res.status(401).json({ error: "Unauthorized" });
    return;
  }

  const email = supabaseUser.email;
  if (!email) {
    res.status(422).json({ error: "Conta sem endereço de e-mail associado." });
    return;
  }

  const supabaseId = supabaseUser.id;
  const { realName, fallbackName } = extractProviderName(supabaseUser);
  const providerAvatarUrl: string | null = supabaseUser.user_metadata?.avatar_url ?? null;

  // ── Step 1: look up by supabase_id (fast path for returning users) ─────────
  let users = await db.select().from(usersTable).where(eq(usersTable.supabaseId, supabaseId)).limit(1);

  if (!users.length) {
    // ── Step 2: look up by email ───────────────────────────────────────────────
    // Handles account linking: user previously registered with email/password,
    // now logging in with Google (same email, different supabase_id).
    // Also catches race conditions between concurrent first requests.
    const byEmail = await db.select().from(usersTable).where(eq(usersTable.email, email)).limit(1);

    if (byEmail.length) {
      // Link the existing email account to this Supabase identity
      const existing = byEmail[0]!;
      const linkFields: Partial<typeof usersTable.$inferInsert> = { supabaseId };

      if (providerAvatarUrl && existing.avatarUrl !== providerAvatarUrl) {
        linkFields.avatarUrl = providerAvatarUrl;
      }
      // Upgrade name if current one is auto-generated and Google provides a real one
      if (realName && isAutoGeneratedName(existing.name, email)) {
        linkFields.name = realName;
      }

      const linked = await db
        .update(usersTable)
        .set(linkFields)
        .where(eq(usersTable.email, email))
        .returning();

      users = linked.length ? linked : byEmail;
    } else {
      // ── Step 3: brand-new user — INSERT ───────────────────────────────────────
      // onConflictDoUpdate handles the (supabase_id) race condition on concurrent
      // first requests that both passed the SELECT check above.
      const inserted = await db
        .insert(usersTable)
        .values({
          supabaseId,
          name: fallbackName,
          email,
          avatarUrl: providerAvatarUrl,
          currency: "BRL",
          language: "pt-BR",
        })
        .onConflictDoUpdate({
          target: usersTable.supabaseId,
          set: {
            name: fallbackName,
            avatarUrl: providerAvatarUrl ?? undefined,
          },
        })
        .returning();

      users = inserted;

      // Fire-and-forget welcome email
      sendWelcomeEmail(email, fallbackName).catch(() => {});
    }
  } else {
    // ── Returning user: sync provider data if needed ───────────────────────────
    const existing = users[0]!;
    const syncFields: Partial<typeof usersTable.$inferInsert> = {};

    // Sync avatar from OAuth provider (e.g. Google profile picture)
    if (providerAvatarUrl && existing.avatarUrl !== providerAvatarUrl) {
      syncFields.avatarUrl = providerAvatarUrl;
    }

    // Sync name from provider only when:
    //   • Provider has a REAL name (from Google metadata, not email-derived)
    //   • AND the DB name looks auto-generated (email prefix or placeholder)
    // This preserves names the user has manually set in Settings.
    if (realName && isAutoGeneratedName(existing.name, email)) {
      syncFields.name = realName;
    }

    if (Object.keys(syncFields).length > 0) {
      const updated = await db
        .update(usersTable)
        .set(syncFields)
        .where(eq(usersTable.supabaseId, supabaseId))
        .returning();
      if (updated.length) users = updated;
    }
  }

  if (!users.length) {
    res.status(500).json({ error: "Falha ao provisionar usuário." });
    return;
  }

  (req as any).user = users[0];
  next();
}

export function getUser(req: Request) {
  return (req as any).user;
}
